name: Crowdin Action

on:
  workflow_dispatch:
  push:
    branches: [dev]

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1

      - name: Remove empty values from JSON
        run: |
          cd assets/i18n
          dart nuke.dart >> $GITHUB_STEP_SUMMARY

      - name: Push out changes to i10n
        run: |
          git config user.name revanced-bot
          git config user.email github@revanced.app
          sudo chown -R $USER:$USER .git
          git add assets/i18n/*.json
          git commit -m "chore(Translation): Remove empty values from JSON" assets/i18n/*.json
          git push origin HEAD:feat/translations
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
